theme: jekyll-theme-dinky
title: Princeton University Library Systems
url: "https://pulibrary.github.io"
permalink: /:year:month:day:title
github_username: pulibrary
website_link: "https://library.princeton.edu/"
